<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="6" ignored="0" total="6" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite1" duration-ms="1899" started-at="2018-05-30T02:29:53Z" finished-at="2018-05-30T02:29:55Z">
    <groups>
    </groups>
    <test name="hottest_mst" duration-ms="1899" started-at="2018-05-30T02:29:53Z" finished-at="2018-05-30T02:29:55Z">
      <class name="testcase.master.hot.BannerTest">
        <test-method status="FAIL" signature="bannerTest(java.util.HashMap)[pri:0, instance:testcase.master.hot.BannerTest@3dfc5fb8]" name="bannerTest" duration-ms="173" started-at="2018-05-30T10:29:54Z" data-provider="banner_mst" finished-at="2018-05-30T10:29:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{path=/v2/mobile/banner, environment=0, code=0, CaseName=banner/正常用例, remark= environmentdev：0master：1, body={"secret": "13c5b701c1ef49c0b032ce41b9bec5c2","uid": "20070", "appVersion": "0.3.3","channelId": 0,"deviceOsType": 2,"uuid": "90E95A72-D188-4010-875D-09EF0AF1ABCC", "clientId": "jc_youxiang_app","accessToken": "93b4673ce823416db1e1df4c012839c2"}}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NumberFormatException">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NumberFormatException: nullat java.lang.Integer.parseInt(Integer.java:542)at java.lang.Integer.parseInt(Integer.java:615)at testcase.master.hot.BannerTest.bannerTest(BannerTest.java:51)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NumberFormatException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bannerTest -->
        <test-method status="FAIL" signature="bannerTest(java.util.HashMap)[pri:0, instance:testcase.master.hot.BannerTest@3dfc5fb8]" name="bannerTest" duration-ms="154" started-at="2018-05-30T10:29:54Z" data-provider="banner_mst" finished-at="2018-05-30T10:29:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{path=/v2/mobile/banner, environment=0, code=10000, CaseName=banner/channelId为不存在的值, remark= environmentdev：0master：1, body={"secret": "13c5b701c1ef49c0b032ce41b9bec5c2","uid": "20070", "appVersion": "0.3.3","channelId": 111111111111111,"deviceOsType": 2,"uuid": "90E95A72-D188-4010-875D-09EF0AF1ABCC", "clientId": "jc_youxiang_app","accessToken": "93b4673ce823416db1e1df4c012839c2"}}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NumberFormatException">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NumberFormatException: nullat java.lang.Integer.parseInt(Integer.java:542)at java.lang.Integer.parseInt(Integer.java:615)at testcase.master.hot.BannerTest.bannerTest(BannerTest.java:51)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NumberFormatException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bannerTest -->
        <test-method status="FAIL" signature="bannerTest(java.util.HashMap)[pri:0, instance:testcase.master.hot.BannerTest@3dfc5fb8]" name="bannerTest" duration-ms="189" started-at="2018-05-30T10:29:54Z" data-provider="banner_mst" finished-at="2018-05-30T10:29:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{path=/v2/mobile/banner, environment=0, code=20000, CaseName=banner/channelId缺失, remark= environmentdev：0master：1, body={"secret": "13c5b701c1ef49c0b032ce41b9bec5c2","uid": "20070", "appVersion": "0.3.3","deviceOsType": 2,"uuid": "90E95A72-D188-4010-875D-09EF0AF1ABCC", "clientId": "jc_youxiang_app","accessToken": "93b4673ce823416db1e1df4c012839c2"}}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NumberFormatException">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NumberFormatException: nullat java.lang.Integer.parseInt(Integer.java:542)at java.lang.Integer.parseInt(Integer.java:615)at testcase.master.hot.BannerTest.bannerTest(BannerTest.java:51)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NumberFormatException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bannerTest -->
      </class> <!-- testcase.master.hot.BannerTest -->
      <class name="testcase.master.channel.SearchNewTownChannelListTest">
        <test-method status="FAIL" signature="searchNewTownChannelListTest(java.util.HashMap)[pri:0, instance:testcase.master.channel.SearchNewTownChannelListTest@3cb1ffe6]" name="searchNewTownChannelListTest" duration-ms="158" started-at="2018-05-30T10:29:54Z" data-provider="searchnewtownchannellist_dev" finished-at="2018-05-30T10:29:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{path=/v2/mobile/ableChannelSecond, remark= environmentdev：0master：1, code=0, body={ "secret": "13c5b701c1ef49c0b032ce41b9bec5c2", "uid": "20070", "appVersion": "0.3.3", "deviceOsType": 2, "uuid": "90E95A72-D188-4010-875D-09EF0AF1ABCC", "clientId": "jc_youxiang_app", "accessToken": "e5722926f28b41449d0620a4fb11cd2d"}, CaseName=新城镇列表/正常用例}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NumberFormatException">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NumberFormatException: nullat java.lang.Integer.parseInt(Integer.java:542)at java.lang.Integer.parseInt(Integer.java:615)at testcase.master.channel.SearchNewTownChannelListTest.searchNewTownChannelListTest(SearchNewTownChannelListTest.java:42)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NumberFormatException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchNewTownChannelListTest -->
      </class> <!-- testcase.master.channel.SearchNewTownChannelListTest -->
      <class name="testcase.master.hot.HotCardTest">
        <test-method status="FAIL" signature="hotCardTest(java.util.HashMap)[pri:0, instance:testcase.master.hot.HotCardTest@467aecef]" name="hotCardTest" duration-ms="167" started-at="2018-05-30T10:29:54Z" data-provider="hotCard_mst" finished-at="2018-05-30T10:29:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{path=/mobile/hotCard, environment=0, code=0, remark= environmentdev：0master：1, casename=hotcard/正常用例, body={ "clientId": "jc_youxiang_app", "secret": "13c5b701c1ef49c0b032ce41b9bec5c2", "uuid": "90E95A72-D188-4010-875D-09EF0AF1ABCC", "appVersion": "0.3.3", "deviceOsType": 2, "accessToken": "93b4673ce823416db1e1df4c012839c2", "page": 0, "size": "1"}}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NumberFormatException">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NumberFormatException: nullat java.lang.Integer.parseInt(Integer.java:542)at java.lang.Integer.parseInt(Integer.java:615)at testcase.master.hot.HotCardTest.hotCardTest(HotCardTest.java:39)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NumberFormatException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- hotCardTest -->
      </class> <!-- testcase.master.hot.HotCardTest -->
      <class name="testcase.master.channel.AbleChannel">
        <test-method status="PASS" signature="ableChannelData()[pri:0, instance:testcase.master.channel.AbleChannel@2a742aa2]" name="ableChannelData" is-config="true" duration-ms="219" started-at="2018-05-30T10:29:53Z" finished-at="2018-05-30T10:29:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ableChannelData -->
        <test-method status="PASS" signature="bannerData()[pri:0, instance:testcase.master.hot.BannerTest@3dfc5fb8]" name="bannerData" is-config="true" duration-ms="9" started-at="2018-05-30T10:29:53Z" finished-at="2018-05-30T10:29:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bannerData -->
        <test-method status="PASS" signature="hotCardData()[pri:0, instance:testcase.master.hot.HotCardTest@467aecef]" name="hotCardData" is-config="true" duration-ms="8" started-at="2018-05-30T10:29:53Z" finished-at="2018-05-30T10:29:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- hotCardData -->
        <test-method status="PASS" signature="newTownChannelListData()[pri:0, instance:testcase.master.channel.SearchNewTownChannelListTest@3cb1ffe6]" name="newTownChannelListData" is-config="true" duration-ms="4" started-at="2018-05-30T10:29:53Z" finished-at="2018-05-30T10:29:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- newTownChannelListData -->
        <test-method status="FAIL" signature="ableChannelTest(java.util.HashMap)[pri:0, instance:testcase.master.channel.AbleChannel@2a742aa2]" name="ableChannelTest" duration-ms="768" started-at="2018-05-30T10:29:53Z" data-provider="ablechannel_mst" finished-at="2018-05-30T10:29:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{path=/v2/mobile/ableChannel, remark= environmentdev：0master：1, code=0, casename=查询频道列表V2不包含精选/正常用例, body={ "secret": "13c5b701c1ef49c0b032ce41b9bec5c2", "appVersion": "0.3.3", "deviceOsType": 2, "uuid": "90E95A72-D188-4010-875D-09EF0AF1ABCC", "clientId": "jc_youxiang_app", "accessToken": "e5722926f28b41449d0620a4fb11cd2d"}}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NumberFormatException">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NumberFormatException: nullat java.lang.Integer.parseInt(Integer.java:542)at java.lang.Integer.parseInt(Integer.java:615)at testcase.master.channel.AbleChannel.ableChannelTest(AbleChannel.java:42)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NumberFormatException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ableChannelTest -->
      </class> <!-- testcase.master.channel.AbleChannel -->
    </test> <!-- hottest_mst -->
  </suite> <!-- Suite1 -->
</testng-results>
